function(add_lib_info src_file)
  if (NOT DEFINED OSTAR_INFO_LLVM_VERSION)
    set(OSTAR_INFO_LLVM_VERSION "NOT-FOUND")
  else()
    string(STRIP ${OSTAR_INFO_LLVM_VERSION} OSTAR_INFO_LLVM_VERSION)
  endif()
  if (NOT DEFINED CUDA_VERSION)
    set(OSTAR_INFO_CUDA_VERSION "NOT-FOUND")
  else()
    string(STRIP ${CUDA_VERSION} OSTAR_INFO_CUDA_VERSION)
  endif()

  set_property(
    SOURCE ${src_file}
    APPEND
    PROPERTY COMPILE_DEFINITIONS
    OSTAR_CXX_COMPILER_PATH="${CMAKE_CXX_COMPILER}"
    OSTAR_INFO_BUILD_STATIC_RUNTIME="${BUILD_STATIC_RUNTIME}"
    OSTAR_INFO_COMPILER_RT_PATH="${COMPILER_RT_PATH}"
    OSTAR_INFO_CUDA_VERSION="${OSTAR_INFO_CUDA_VERSION}"
    OSTAR_INFO_DLPACK_PATH="${DLPACK_PATH}"
    OSTAR_INFO_DMLC_PATH="${DMLC_PATH}"
    OSTAR_INFO_GIT_COMMIT_HASH="${OSTAR_GIT_COMMIT_HASH}"
    OSTAR_INFO_GIT_COMMIT_TIME="${OSTAR_GIT_COMMIT_TIME}"
    OSTAR_INFO_HIDE_PRIVATE_SYMBOLS="${HIDE_PRIVATE_SYMBOLS}"
    OSTAR_INFO_INDEX_DEFAULT_I64="${INDEX_DEFAULT_I64}"
    OSTAR_INFO_INSTALL_DEV="${INSTALL_DEV}"
    OSTAR_INFO_LLVM_VERSION="${OSTAR_INFO_LLVM_VERSION}"
    OSTAR_INFO_PICOJSON_PATH="${PICOJSON_PATH}"
    OSTAR_INFO_RANG_PATH="${RANG_PATH}"
    OSTAR_INFO_ROCM_PATH="${ROCM_PATH}"
    OSTAR_INFO_SUMMARIZE="${SUMMARIZE}"
    OSTAR_INFO_USE_ALTERNATIVE_LINKER="${USE_ALTERNATIVE_LINKER}"
    OSTAR_INFO_USE_AOT_EXECUTOR="${USE_AOT_EXECUTOR}"
    OSTAR_INFO_USE_CMSISNN="${USE_CMSISNN}"
    OSTAR_INFO_USE_CPP_RPC="${USE_CPP_RPC}"
    OSTAR_INFO_USE_CPP_ROSTAR="${USE_CPP_ROSTAR}"
    OSTAR_INFO_USE_CUDA="${USE_CUDA}"
    OSTAR_INFO_USE_CUDNN="${USE_CUDNN}"
    OSTAR_INFO_USE_CUSTOM_LOGGING="${USE_CUSTOM_LOGGING}"
    OSTAR_INFO_USE_FALLBACK_STL_MAP="${USE_FALLBACK_STL_MAP}"
    OSTAR_INFO_USE_GRAPH_EXECUTOR_CUDA_GRAPH="${USE_GRAPH_EXECUTOR_CUDA_GRAPH}"
    OSTAR_INFO_USE_GRAPH_EXECUTOR="${USE_GRAPH_EXECUTOR}"
    OSTAR_INFO_USE_GTEST="${USE_GTEST}"
    OSTAR_INFO_USE_IOS_RPC="${USE_IOS_RPC}"
    OSTAR_INFO_USE_KHRONOS_SPIRV="${USE_KHRONOS_SPIRV}"
    OSTAR_INFO_USE_LIBBACKTRACE="${USE_LIBBACKTRACE}"
    OSTAR_INFO_USE_LIBTORCH="${USE_LIBTORCH}"
    OSTAR_INFO_USE_LLVM="${USE_LLVM}"
    OSTAR_INFO_USE_MKL="${USE_MKL}"
    OSTAR_INFO_USE_OPENMP="${USE_OPENMP}"
    OSTAR_INFO_USE_PAPI="${USE_PAPI}"
    OSTAR_INFO_USE_PROFILER="${USE_PROFILER}"
    OSTAR_INFO_USE_RANDOM="${USE_RANDOM}"
    OSTAR_INFO_USE_RPC="${USE_RPC}"
    OSTAR_INFO_USE_SORT="${USE_SORT}"
    OSTAR_INFO_USE_STACKVM_RUNTIME="${USE_STACKVM_RUNTIME}"
    OSTAR_INFO_USE_TARGET_ONNX="${USE_TARGET_ONNX}"
    OSTAR_INFO_USE_THREADS="${USE_THREADS}"
    OSTAR_INFO_USE_THRUST="${USE_THRUST}"
    OSTAR_INFO_USE_CURAND="${USE_CURAND}"
    OSTAR_INFO_USE_CCACHE="${USE_CCACHE}"
    OSTAR_INFO_BACKTRACE_ON_SEGFAULT="${BACKTRACE_ON_SEGFAULT}"
  )

endfunction()
